default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 
  pool: 5

development:
  <<: *default
  database: studentApp_development
  # database: <%= ENV['RDS_DB_NAME'] %>
  # username: <%= ENV['RDS_USERNAME'] %>
  # password: <%= ENV['RDS_PASSWORD'] %>
  # host: <%= ENV['RDS_HOSTNAME'] %>
  # port: <%= ENV['RDS_PORT'] %>

test:
  <<: *default
  database: studentApp_test


production:
  <<: *default
  database: studentApp_production
  username: studentApp
  password: <%= ENV['STUDENTAPP_DATABASE_PASSWORD'] %>
